// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnttslbqkvfzadqiiyza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudHRzbGJxa3ZmemFkcWlpeXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4MTkxNzUsImV4cCI6MjA5OTM5NTE3NX0.pG-DIciftHeXBDx451dTMLreimZLIClE4hVlC5l9f0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});